Fix recurring BatchUpdateErrors on restart
We've been seeing this error in all running instances with some
regularity:

```
WARN  | backtick.engine |
Unable to run job backtick.core/revive-killed-jobs
java.sql.BatchUpdateException: Batch entry 0 update backtick_queue
set state = 'queued', priority = '2016-02-10 15:55:31.437000 -08:00:00',
update_at = now()
where id = 242 and state = 'running' was aborted.
```

Turns out it was a single character typo. Fixed.